### ISSUE TITLE
fix the dev rockspec source

### ISSUE THREAD

**Issue by teto** [alerque/cldr-lua#4]
I am doing some due changes to the lua package set in nixpkgs https://github.com/NixOS/nixpkgs/pull/190067 and updating cldr fails 
because the updater runs the wrong command:
```
nix-prefetch-git --fetch-submodules --quiet https://github.com/alerque/cldr-lua.git --rev refs/tags/master
Initialized empty Git repository in /tmp/git-checkout-tmp-jOX48YMM/cldr-lua/.git/
fatal: couldn't find remote ref refs/tags/master
From https://github.com/alerque/cldr-lua
 * branch            HEAD       -> FETCH_HEAD
fatal: Not a valid object name 
```
Looking at https://github.com/alerque/cldr-lua/blob/master/cldr-dev-0.rockspec the source contains tag = "master".  https://github.com/alerque/cldr-lua/blob/master/cldr.rockspec.in assumes a tag but "master" was used (incorrectly) as a tag, according to the spec https://github.com/luarocks/luarocks/wiki/Rockspec-format "tag" should become "branch".

**Comment by alerque** [comment]
Hm, yes. The latest LuaRocks does not care about this difference and it's ugly to work around, hence why that `tag = branch` bit. As we recently found out on some Lunarmodules projects though this hinders older LuaRocks.

I'll update this rockspec to the solution we came up with.

**Comment by teto** [comment]
luarocks-nix (https://github.com/nix-community/luarocks-nix) is based on the latest luarocks but it adds our own code to generate nix expressions. If I could consider a tag as a tag an a branch as a branch it would be helpful as a fellow nixer :partying_face: 
(if you were a non-nixer, I would maybe add a if tag == "master" -> it's a branch xD)

**Comment by alerque** [comment]
This reason we bump into this is because of the difference between LuaRocks concept of dev (scm/cvs) rockspecs vs. tagged ones. First, the switch from branch to tag when doing a release means an error prone manual edit. The file type is full Lua, so automating is potentially brittle. To add insult to injury it is impossible to test with `tag =` before actually tagging. With new versions of LuaRocks it treats `branch =` as `tag_or_branch`, which is handy.

But since this breaks old LuaRocks anyway I don't mind fixing it with our other mostly-testable solution—some Lua logic in the rockspec file.

**Comment by alerque** [comment]
I fixed the issue in the dev rockspec, but it occures to me — why is Nix not using the release rockspec? There are up and down sides. Downside being rockspec v1 doesn't have some fields like testing tooling, issue links, etc. Upside would be the correct version information in LuaRocks generated manifests. I guess it depends on whether Nix updates a manifest or not.

**Comment by teto** [comment]
>  why is Nix not using the release rockspec?

so yeah I was experimenting with something, to use luarocks packages as neovim plugins and so I enabled `luarocks --dev` otherwise it wouldn't show some packets, with the sideeffect of picking cldr's dev rockspec over the stable release. 
Still not sure how I will proceed about this, probably enable `--dev` conditionnally to something, like if it's a neovim plugin or if it's specified in  maintainers/scripts/luarocks-packages.csv

**Comment by teto** [comment]
btw thanks it seems to have solved the issue !
